spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vanilsonsantos/cloud-config-properties
          searchPaths: telecom-platform
          clone-on-start: true

server:
  port: 8888

